### ISSUE TITLE
OpenTelemetry: Test the new example for opentelemetry

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#789] opened 2023-11-21 10:55 UTC
Kai wrote support for OpenTelemetry. Verify that somebody else can set it up.

**Comment by k-klemmer** [comment] 2024-01-29 08:50
I accidentally closed it. I'm waiting for @christiangoerdes to go over the issue with me, since i couldn't reproduce it. So it is still unclear if my refactoring fixed the issue or not.

**Closed** 2024-02-28 12:16 UTC
